### ISSUE TITLE
Windows-style line endings cause panic on Lua 5.1 example

### ISSUE THREAD

**Issue by fuwn** [osa1/lexgen#1]
Haven't experimented much with the core package yet but right off the bat I noticed that when running the Lua example using Unix-style line endings, it works fine however, running the example using Windows-style line endings, it panics.

**Comment by osa1** [comment]
Thanks for trying this and reporting. I'm not sure what you mean by panics, I couldn't make it panic when I inserted some random `\r\n`s in the Lua files distributed with Lua 5.1.5 tarball. I get lexer errors, but no panics. Could you show me the full output please?

I just pushed a commit for treating `\r\n` as whitespace in the Lua lexer, which fixes the lexer errors when the file uses `\r\n` as line endings.

For the record, the Lua parser is not supposed to be a production-ready Lua lexer. It's just an example that demonstrates all features of lexgen (lexer and users states, use of the handler type etc.). I'm still happy to fix any bugs in it though.

**Comment by fuwn** [comment]
My fault, I did mean a lex' error not a panic. Nonetheless, thank you for fixing and I understand about the production-ready aspect, just didn't want someone to come across this repository and the first thing they get is a lex'ing error when experimenting.
