### ISSUE TITLE
Confusing match reset behavior in initial state

### ISSUE THREAD

**Issue by osa1** [osa1/lexgen#12]
(Issue originally discovered in #11)

https://github.com/osa1/lexgen/blob/faa2af333dd79cc0f9f7ae099c72678b732404de/src/dfa/codegen.rs#L336

The line above resets the current match every time we're back at the initial state (e.g. after `switch(LexerRule::Init)`, or simply by looping in the initial state).

This behavior is a bit confusing, and it seems hacky too. I don't remember the original motivation for implementing this, but if I remove this special case and look at the broken tests, it seems like we rely on this to skip whitespace:

```
rule Init {
    $whitespace,
    ...
}
```

In a rule like this, if we reset the current match every time we reach the initial state, that means the skipped whitespace will never be a part of the current match. So if I have other cases in this rule where I use `lexer.match_()` I won't ever see the skipped characters in the match.

In addition to being perhaps a bit counter-intuitive, this is a special case in the initial rule, so if I have a different rule I can't easily have the same behavior (I need to count the amount of whitespace matched, and manually drop the prefix).

Reminder: other than the special case above, we only reset the match after returning a token.

---

One potential fix would be to never implicitly reset the match, and implement a method for resetting the current match.

For skipping whitespace concisely, we could either desugar the rule syntax without RHS (`$whitespace,` above) to "reset and continue", or keep it the way it is (just "continue") and implement skipping whitespace as:

```
rule Init {
    $whitespace => |mut lexer| {
        lexer.reset_match();
        lexer.continue_();
    },
    ...
}
``` 

Either way there will be some breakage. If we desugar it as "reset and continue" then uses in non-initial rules will break. If we desugar it as just "continue" then uses in the initial rule will break.

**Comment by osa1** [comment]
Currently, there are two special cases in `Init` state:

1. `Init` accepts end-of-input, the iterator to yield `None`. Other states do not accept end-of-input.
2. Whenever loop back to the beginning of `Init` rule we reset the current match. In practice, the only case where this is useful is when skipping whitespace, with something like `$$whitespace,`.

I think (1) kinda makes sense, and so far I don't find any problems with it in practice. (see also #13)

This issue is to fix (2).

Since we may want skip but include in the match, or skip and reset the match, we have two options:

- Don't reset match by default, have a `reset_match` method
- Have two different syntax for resetting skip and non-resetting skip

**Comment by glennschmidt** [comment]
>  desugar the rule syntax without RHS ($whitespace, above) to "reset and continue"

This option makes the most sense to me. Especially since that's how the Readme describes it already.

Then the docs for the `continue_()` method should be updated to make clear that method will not reset the match.

> Init accepts end-of-input, the iterator to yield None. Other states do not accept end-of-input.

It would also be good to add this to the docs too, because it wasn't obvious to me that rule sets must always return back to the initial rule before the end of the input in order to terminate lexing without an error. I would have thought if there is no more input, the lexer's job is finished by definition.

**Comment by osa1** [comment]
> It would also be good to add this to the docs too, because it wasn't obvious to me that rule sets must always return back to the initial rule before the end of the input in order to terminate lexing without an error.

I documented this in https://github.com/osa1/lexgen/pull/63. Could you take a look and let me know if it clarifies things?

> I would have thought if there is no more input, the lexer's job is finished by definition.

In my experience the rules other than the initial one are usually for complicated literals (multi-line strings, raw strings etc.) or comments, and you want those to be terminated. For example, if you look at the Lua 5.1 example in the repo, none of 6 non-init rules can accept end-of-input.
