### ISSUE TITLE
Support negated character sets?

### ISSUE THREAD

**Issue by FranklinChen** [osa1/lexgen#32]
I noticed that negated character sets are not supported? Is there a reason?

**Comment by osa1** [comment]
It will be implemented, see #24.

I'm curious about your use case, could you say a few words about why you need this feature?

**Comment by FranklinChen** [comment]
I use negated character sets all the time with other lexer generators; most of my important tokens involve negation. For example, "starts with & and then is followed by anything other than a number or colon or space", so that "&x_0=é(y)" is a token.

**Comment by osa1** [comment]
Thanks for the example. I'm closing this as duplicate of #24.
