### ISSUE TITLE
Implement Default for Loc

### ISSUE THREAD

**Issue by MiSawa** [osa1/lexgen#44]
Thank you for the amazing lexer!

The generated lexer seems to be 99% compatible with [what lalrpop takes](http://lalrpop.github.io/lalrpop/lexer_tutorial/002_writing_custom_lexer.html). The only incompatibility is the lack of `Default` implementation for `lexgen_util::Loc`, which lalrpop [uses](https://github.com/lalrpop/lalrpop/blob/fc9986c725d908a60b11d8480711afa33f7f3564/lalrpop/src/lr1/codegen/parse_table.rs#L219) to initialize the location.
If there's no reason not to implement it, it'd be great to have it implemented so that the following just works (with `type Location = lexgen_util::Loc` and `type Error = lexgen_util::LexerError<MyError>` defined in the `extern` section of the `.lalrpop` file).
```rust
let lexer = Lexer::new(query); // The lexgen-generated lexer
let query = QueryParser::new() // The lalrpop-generated parser
    .parse(query, lexer)
    .unwrap();
```

**Comment by osa1** [comment]
Thanks for reporting this and the PR.

lalrpop compatibility has always been a goal since the early days, but I never got around using lexgen with lalrpop as I originally planned, instead I wrote my own parsers.

Btw, if you're interested in implementing a lexgen-lalrpop example or a test I would be happy to merge that as well :-)

**Comment by MiSawa** [comment]
Opened PR that adds examples! :) https://github.com/osa1/lexgen/pull/46

**Comment by MiSawa** [comment]
Hi, I'm wondering if this change can be published so we don't need to specify dependency via `lexgen = { git = "..." }` :)

**Comment by osa1** [comment]
> Hi, I'm wondering if this change can be published so we don't need to specify dependency via lexgen = { git = "..." } :)

Done :)

**Comment by MiSawa** [comment]
Awesome, thank you!!
